version: "3.7"
services:
  api_service:
    image: 'coworker-postgres:latest'
    build: .
    ports:
      - 8070:8070
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/security_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=vfrcbv2005
    depends_on:
      - db
  db:
    image: "postgres:latest"
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=vfrcbv2005
      - POSTGRES_DB=security_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


