version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8070:8070
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/security_db?createDatabaseIfNotExist=true
    depends_on:
      mysqldb:
          condition: service_healthy

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: security_db
      MYSQL_USER: maksim
      MYSQL_PASSWORD: vfrcbv2005
      MYSQL_ROOT_PASSWORD: vfrcbv2005
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 1
networks:
  springapimysql-net: