version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coworker_db
    ports:
      - "3307:3307"
    networks:
      - "coworkerNet"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      - db
    networks:
      - "coworkerNet"
networks:
  coworkerNet:
    driver: bridge
